encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path('newpage', views.newpage, name='newpage'),
    path('wiki/<str:entry>', views.entry, name='entry'),
    path('edit/<str:entry>', views.edit, name='edit'),
    path('wiki/', views.randomPage, name='random'),
    path('search', views.search, name='seach'),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import random
from django import forms
from . import util
import markdown2

class Create(forms.Form):
    title = forms.CharField(label='Title')
    text_box = forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder':'Enter text here'}))

class Edit(forms.Form):
    text_box = forms.CharField(label='', widget=forms.Textarea())

class Search(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'class': 'searchbar', 'placeholder': 'Search'}))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        'form': Search(),
    })

def newpage(request):
    if request.method == 'POST':
        new_entry = Create(request.POST)
        if new_entry.is_valid():
            title = new_entry.cleaned_data['title']
            text = new_entry.cleaned_data['text_box']
            if title not in util.list_entries():
                util.save_entry(title, text)
                return render(request, "encyclopedia/entry.html", {
                    'title': title,
                    'text': markdown2.markdown(util.get_entry(title)),
                    'form': Search(),
                })
            else:
                return render(request, 'encyclopedia/error.html', {
                    'error': 'This entry has already been made!',
                    'form': Search(),
                })

    return render(request, 'encyclopedia/newpage.html', {
        'create': Create(),
        'form': Search(),
    })


def entry(request, entry):
    if entry in util.list_entries():
        text = util.get_entry(entry)
        return render(request, "encyclopedia/entry.html", {
            'title': entry,
            'text': markdown2.markdown(text),
            'form': Search(),
        })
    else: 
        return render(request, "encyclopedia/error.html", {
        'error': 'Invalid Entry Title',
        'form': Search(),
    })


def edit(request, entry):
    if request.method == 'POST':
        new_entry = Edit(request.POST)
        if new_entry.is_valid():
            text = new_entry.cleaned_data['text_box']
            util.save_entry(entry, text)
            return render(request, 'encyclopedia/entry.html', {
                'title': entry,
                'text': markdown2.markdown(util.get_entry(entry)),
                'form': Search(),
            })
        
    else:
        text = util.get_entry(entry)
        
        return render(request, 'encyclopedia/edit.html', {
            'title': entry,
            'edit': Edit(initial={'text_box': text}),
            'form': Search(),
        })


def randomPage(request):
    entries = util.list_entries()
    e = random.choice(entries)
    return entry(request, e)


def search(request):
    searched = Search(request.POST)
    if searched.is_valid():
        search = searched.cleaned_data['search']
        entries = util.list_entries()
        matched = []
        for x in entries:
            if search.lower() == x.lower():
                text = markdown2.markdown(util.get_entry(x))
                return render(request, 'encyclopedia/entry.html', {
                    'title': x,
                    'text': text,
                    'form': Search(),
                })
            if search.lower() in x.lower():
                matched.append(x)
        return render(request, 'encyclopedia/search.html', {
            'title': search,
            'matched': matched,
            'form': Search(),
        })

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Edit {{title}}
{% endblock %}

{% block body %}
    <form action="/edit/{{title}}" method='POST'>
        {% csrf_token %}
        <div class='text_box'>
        <div >{{ edit }}</div>
        <input class='button' type='submit' value='Edit Page'>
        </div>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
(%load static %)

{% block title %}
    {{ title }}
{% endblock %}

{% block nav %}
    <div>
        <a href=/edit/{{title}} class = 'toolbar-links'>Edit Page</a>
    </div>
{% endblock %}

{% block body %}
    {{ text |safe}}
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h4 class='alert alert-danger'>Error! {{Error}}</h4>
    <div><a href="{% url 'wiki:index' %}">Return To Homepage</a></div>
    <a href="{% url 'wiki:newpage' %}">Create Entry</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul class='list'>
        {% for entry in entries %}
            <li><a href=/wiki/{{entry}}>{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="post" action="/search">
                    {% csrf_token %}
                    {{form.search}}
                </form>
                <div>
                    <a class = 'toolbar-links' href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a class = 'toolbar-links' href="{% url 'wiki:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a class = 'toolbar-links' href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Entry
{% endblock %}

{% block body %}
    <h1>Create New Entry Page</h1>
    <form class='h' action="{% url 'wiki:newpage' %}" method='post'>
        {% csrf_token %}
        <div class='new_title'>Title: {{ create.title }}</div>
        <div class='text_box'>{{ create.text_box }}</div>
        <input class='button' type='submit' value='Save Post'>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Search '{{title}}'
{% endblock %}

{% block body %}
    <h1>Search for '{{title}}'</h1>
    {% for entry in matched %}
        <li><a href=/wiki/{{entry}}>{{ entry }}</a></li>
    {% endfor %}
{% endblock %}